### PR TITLE
Fix for github issue #1100

### PR DESCRIPTION
**Pull request by wachi-yoshitaka**
Fixed an issue which is occurring 'Malformed Token' when specified device id has a semicolon.

This is not the best way.
Because, if device id is specified similar to 'connection string' (has both a semicolon and an equal sign), the code still has problems.
However, in the case that device id has one of a semicolon and an equal sign, the fix is helpful.

## Checklist
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/.github/CONTRIBUTING.md).
- [x] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [x] This pull-request is submitted against the `master` branch.

### CODE REVIEW

**Comment by timtay-microsoft** [comment]
Can you provide a few unit tests around this scenario? The DeviceClientConnectionStringTests class should be a good place to test connection strings where the deviceId contains semicolons

**Comment by wachi-yoshitaka** [comment]
I have modified the unit tests.
I added a semicolon to the device id of the unit test.

I checked the following.
- The source code before fix gets NG as result of unit test.
- The source code after fix gets OK as result of unit test.

**Comment by timtay-microsoft** [comment]
These unit tests look good, now. I'll work to get this merged in soon. Thanks for the PR!

**Comment by timtay-microsoft** [comment]
I will also need you to sign the Contributor License Agreement before I can merge this in, if you haven't already

**Comment by wachi-yoshitaka** [comment]
Thanks.
I have signed the CLA.

**Pull request merged**
