### PR TITLE
Add DeviceNotOnline to error codes

### PR DESCRIPTION
**Pull request by pregress**
## Checklist
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-iot-sdk-csharp/blob/main/.github/CONTRIBUTING.md).
- [x] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [x] This pull-request is submitted against the `main` branch.

## Description of the changes
Added the error code: 404103 for Device online. So users can handle this error gracefully. 

## Reference/Link to the issue solved with this PR (if any)
Fixes: https://github.com/Azure/azure-iot-sdk-csharp/issues/3442

### CODE REVIEW

**Review by timtay-microsoft — APPROVED** [review]

**Comment by pregress** [comment]
Any reason why .NET 6 pipelines fail? Can't view the error since it azure devops.

**Comment by timtay-microsoft** [comment]
We have some security rules in place that make it so forked PRs (like this one) can't access the credentials we use during our integration testing. Could you convert these changes into a branch on this repo instead?

**Comment by pregress** [comment]
> We have some security rules in place that make it so forked PRs (like this one) can't access the credentials we use during our integration testing. Could you convert these changes into a branch on this repo instead?

@timtay-microsoft I do not have permissions to create a branch on this repo

**Comment by timtay-microsoft** [comment]
Ah, my apologies. I'll go ahead and create that branch for you. #3450 should be merged in shortly

**Comment by timtay-microsoft** [comment]
Your fix has been merged in #3450, so I'll close this PR

**Pull request closed without merging**
