### PR TITLE
Adding all commits in master to preview

### PR DESCRIPTION
**Pull request by vinagesh**
…ncy to 2.4.4

## Checklist
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [ ] This pull-request is submitted against the `master` branch.

## Description of the changes
Adding all commits in master to preview.

### CODE REVIEW

**Comment by abhipsaMisra** [comment]
Isn't 6842afebb2c3166f239263d65d2535729569cbe3 required on master?

**Comment by vinagesh** [comment]
> Isn't [6842afe](https://github.com/Azure/azure-iot-sdk-csharp/commit/6842afebb2c3166f239263d65d2535729569cbe3) required on master?
This test only exists on preview and hence was not updated/fixed in master corresponding to the change that added the additional message parameter.

**Pull request merged**
