### PR TITLE
Merge in latest from main

### PR DESCRIPTION
**Pull request by drwill-ms**

### CODE REVIEW

**Review by brycewang-microsoft — APPROVED** [review]

**Comment by timtay-microsoft** [comment]
@drwill-ms  We typically don't squash when merging from main to preview, FYI. Be careful with that auto-squash

**Comment by drwill-ms** [comment]
> @drwill-ms We typically don't squash when merging from main to preview, FYI. Be careful with that auto-squash

Totally right. Thanks for catching that.

**Pull request merged**
