### PR TITLE
Delete duplicate provisioning/device/samples/Getting Started directory

### PR DESCRIPTION
**Pull request by ngastelum-ms**

### CODE REVIEW

**Review by abhipsaMisra — APPROVED** [review]

**Comment by abhipsaMisra** [comment]
Confirm that build scripts refer to the collect folder when they try to build the samples in our nightly run

**Review by drwill-ms — APPROVED** [review]

**Comment by drwill-ms** [comment]
Does the solution reference this by case at all?

**Comment by ngastelum-ms** [comment]
> Does the solution reference this by case at all?

I double checked and the solution only refers to the lowercase folder, it used to reference the uppercase one before I made the change in a previous PR

**Pull request merged**
