### PR TITLE
Updating LTS branch information.

### PR DESCRIPTION
**Pull request by CIPop**
Updating LTS information: 
* lts_2018_01 active
* lts_07_2017  out of support

### CODE REVIEW

**Comment by yzhong94** [comment]
lts
While you are at it, can you also change the picture?

**Comment by CIPop** [comment]
> While you are at it, can you also change the picture?

What needs to change? Also: was this generated using some tool that I can re-use to change it?

**Comment by yzhong94** [comment]
@CIPop note that in the new picture, i changed the major version increase to minor version increase

**Comment by CIPop** [comment]
> @CIPop note that in the new picture, i changed the major version increase to minor version increase

Oh, the one you've attached _is_ the new image :). I understand now - I'll submit another PR.

**Comment by CIPop** [comment]
> While you are at it, can you also change the picture?

Done

**Comment by yzhong94** [comment]
:shipit:

**Pull request merged**
