### PR TITLE
combine getting started folders

### PR DESCRIPTION
**Pull request by patilsnr**

### CODE REVIEW

**Comment by schoims** [comment]
Could you update sample links in iothub/device/samples/readme.md accordingly?

**Review by timtay-microsoft — APPROVED** [review]

**Review by abhipsaMisra — APPROVED** [review]

**Review by brycewang-microsoft — COMMENTED** [review]
Did we decide to name the sample sub-folders like "getting started" without capitals?

This is a good question. I noticed in iothub they are lowercase and in provisioning they're uppercase. I think lowercase is better since all our `how to` and `solutions` folders are lowercase and I can update these to be consistent.

**Review by brycewang-microsoft — APPROVED** [review]

**Comment by patilsnr** [comment]
> Did we decide to name the sample sub-folders like "getting started" without capitals?
> 
> This is a good question. I noticed in iothub they are lowercase and in provisioning they're uppercase. I think lowercase is better since all our `how to` and `solutions` folders are lowercase and I can update these to be consistent.

**Review by drwill-ms — APPROVED** [review]

**Pull request merged**
