### PR TITLE
fix(e2e-tests): Remove ASC validation for security message tests

### PR DESCRIPTION
**Pull request by abhipsaMisra**

### CODE REVIEW

**Comment by drwill-ms** [comment]
Does anything change for our E2E setup script?

**Review by drwill-ms — APPROVED** [review]

**Review by andyk-ms — APPROVED** [review]

**Comment by abhipsaMisra** [comment]
> Does anything change for our E2E setup script?

I haven't changed our E2E script yet since I was on the fence about not having the security solution enabled on the hub, even if we don't validate the routing anymore. 
Pro - we enable the relevant feature and perform the operation.
Con - additional infra costs.

**Comment by drwill-ms** [comment]
> I haven't changed our E2E script yet since I was on the fence about not having the security solution enabled on the hub, even if we don't validate the routing anymore.
> Pro - we enable the relevant feature and perform the operation.
> Con - additional infra costs.

Make it optional, off by default?

**Comment by abhipsaMisra** [comment]
> 

I'll give it a try - my intro to working with bicep files.

**Comment by abhipsaMisra** [comment]
Closing this in favor of #2253

**Pull request closed without merging**
