### PR TITLE
Specify to output the new snupkg format

### PR DESCRIPTION
**Pull request by drwill-ms**
Perhaps one step closer to https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

I'd have preferred to add symbols directly to the nupkg file, but apparently that is not the way we do things these days.

### CODE REVIEW

**Comment by drwill-ms** [comment]
Not ready to push these to nuget yet. We'll attach them to our release as usual and I'll figure out if we want to publish there, somewhere else, or not.

**Comment by abhipsaMisra** [comment]
We can remove the include-source and include-symbols from our CLI command as well: https://github.com/Azure/azure-iot-sdk-csharp/blob/master/build.ps1#L143

**Comment by drwill-ms** [comment]
> We can remove the include-source and include-symbols from our CLI command as well: https://github.com/Azure/azure-iot-sdk-csharp/blob/master/build.ps1#L143

In the meantime, it doesn't hurt to include them on the command.

**Pull request merged**
