### PR TITLE
release: Bump versions for latest release

### PR DESCRIPTION
**Pull request by jamdavi**
### Improvements and Features

- Add additional logs to MQTT implementation
- Added extra comments to clarify true and false in dispose (#1805)
- Make the DeviceClient and ModuleClient extensible (#1802)
- Handle Twin failures using Amqp (#1796)

### Bug Fixes

- Fix AMQP layer not releasing a semaphore for method links after unsubscribing from methods (#1831)
- Fix semaphore usage within InternalClient (#1823)
- UnixDomainSocketEndPoint is available in .NET 2.1 and greater (#1816)
- IoTHub Exception for Get and Patch Twin failures (#1815)
- Fix MqttTransportHandler to not await on user supplied C2D callback
- Update dotnetty task calls to use ConfigureAwait(true)
- Update MqttTransportHandler to not use SemaphoreSlim.WaitAsync(TimeSpan, CancellationToken)

### Improvements 

- Update xml comments and backwards compatible changes to the ServiceClient base class that improve the amount of methods to override.

### CODE REVIEW

**Comment by timtay-microsoft** [comment]
Why is the service client bump a minor version for xml comment changes? Is this to leave room for making the previous version the LTS?

**Comment by timtay-microsoft** [comment]
The release notes for the changes I made look good to me, otherwise.

**Comment by jamdavi** [comment]
> Why is the service client bump a minor version for xml comment changes? Is this to leave room for making the previous version the LTS?

Good catch. There are changes to ServiceClient abstract class that were rolled into the XML change. Let me edit the release notes to reflect that.

https://github.com/Azure/azure-iot-sdk-csharp/blame/master/iothub/service/src/ServiceClient.cs#L170-L174

https://github.com/Azure/iot-sdks-internals/pull/228/files?diff=split&w=1#diff-b3e67e93c9bae5a283b1d5c913e21f639ff3669d7210faa88b710fccc0d1e35fR618

**Review by vinagesh — APPROVED** [review]

**Comment by vinagesh** [comment]
Looks good other than updating the release notes to reflect why ServiceClient has a minor version bump

**Pull request merged**
