### PR TITLE
Delete duplicate service getting started sample directory

### PR DESCRIPTION
**Pull request by ngastelum-ms**

### CODE REVIEW

**Comment by patilsnr** [comment]
Did we rebuild the solution file after these were deleted? I can't remember if that makes a difference.

**Review by abhipsaMisra — APPROVED** [review]
This also needs to go
https://github.com/Azure/azure-iot-sdk-csharp/tree/previews/v2/provisioning/device/samples/Getting%20Started

**Review by patilsnr — APPROVED** [review]

**Comment by ngastelum-ms** [comment]
> Did we rebuild the solution file after these were deleted? I can't remember if that makes a difference.

The solution file is already updated, there's no reference to the uppercase directory so should be fine.

**Review by drwill-ms — APPROVED** [review]
Does the solution reference this by case, at all?

**Pull request merged**
