### PR TITLE
Set remote certificate validation callback for WebSocket connections

### PR DESCRIPTION
**Pull request by jussi-raunio-abb**
## Checklist
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
  - There were no unit tests for the methods that I changed in the first place.
- [x] This pull-request is submitted against the `master` branch.

## Description of the changes
- Remove private key checks from `ClientFactory`.
- Set remote certificate validation callback for WebSocket connections.
  - Since .NET core does not use global certificate validation callbacks, each instance has its own remote certificate validation callback. Unfortunately, the `WebSocketOptions` in .NET standard does not exposed a remote certificate callback property. When a library is used from .NET core, there is no way to set WebSocket's remote certificate callback. This PR sets the remote certificate callback through reflection. 
- Add remote certificate callback property to `SecurityProviderX509` to be used by the provisioning service.

## Reference/Link to the issue solved with this PR (if any)
We are using .NET core in Linux with custom OpenSSL client certificate engine. Since .NET does not expose OpenSSL interface, we have configured OpenSSL engine to be autoloaded. So, when a TLS connection is established, our custom OpenSSL engine completes the handshake by providing a private key for the certificate.

SDK does not need to know anything about OpenSSL or our custom engine. However, SDK needs to allow certificate validation to happen outside the application. Basically this means that:
- SDK should allow certificates without private key.
- SDK should allow setting a custom certificate validation callback for provision and device connections.

### CODE REVIEW

**Comment by jussi-raunio-abb** [comment]
I am not sure what `csharp-westcentralus` check is. Should I do something to it?

**Comment by jussi-raunio-abb** [comment]
> 
> 
> /azp run

The pipeline also fails in master. What are you expecting me to do?

**Comment by abhipsaMisra** [comment]
> > /azp run
> 
> The pipeline also fails in master. What are you expecting me to do?

It failed while running the tests. Are you able to run the unit tests at your end and verify that everything is green?

**Comment by jussi-raunio-abb** [comment]
If I checkout master and run unit tests there using Visual Studio 2019 test runner, I am getting test failures. Same test failures are visible also in my branch since I branched it from master. Should I use another branch?

What is the proper way to run unit tests? I couldn't find any documentation about tests. It seems that running them from Visual Studio does not work in my environment (this is from master):
image

**Comment by abhipsaMisra** [comment]
@jussi-raunio-abb Visual studio test runner will pick all tests available within the solution, including end to end tests. Our end-to-end tests requires some prerequisite configuration, the details of which are available [here](https://github.com/Azure/azure-iot-sdk-csharp/tree/master/e2e/test/prerequisites) (if you're interested).
For the purpose of this PR, it is sufficient that you run the unit tests at your end first. To do this, in your Visual Studio test explorer, deselect the E2ETests project, and run everything else. 
image

You can also run the E2E tests if you want, but they do require some infra setup. The E2E tests will be run in pipeline for this PR as well.

**Comment by abhipsaMisra** [comment]
@jussi-raunio-abb - an update, the above failure is likely caused due to the pipeline being unable to run E2E tests from forked branches. I am working to get this fixed.

**Comment by jussi-raunio-abb** [comment]
@abhipsaMisra thanks! I ran unit tests from master branch, but unfortunately I am still observing failing tests: 
image

I selected everything but E2E tests, but for some reason it refused to run all of them. If these are unit tests, those shouldn't require any special environment setup, right? I am using Visual Studio 2019 and pulled the master branch from original repository.

**Comment by abhipsaMisra** [comment]
Updating here as well: the pipeline build issue has been resolved; PRs can be run from forked branches. Other discussions about this PR (and particularly, the scenario it attempts to address) are currently being carried out over email.

**Comment by abhipsaMisra** [comment]
@jussi-raunio-abb I am closing this PR; the progress of this work item can be tracked via #1363

**Pull request closed without merging**
