### PR TITLE
Add proxy handling to HttpClientHelper.httpClientObjWithPerRequestTim…

### PR DESCRIPTION
**Pull request by jenoola**
…eout

## Checklist
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [X] This pull-request is submitted against the `master` branch.

## Description of the changes

The change fixes proxy support for HTTP requests sent by service client or registry manager if custom operation timeout is specified and it is not equal to default operation timeout.

### CODE REVIEW

**Comment by jenoola** [comment]
@abhipsaMisra this object is used when timeout is specified and it is not the same as the default timeout. I haven't added it, I just corrected proxy handling.

**Comment by abhipsaMisra** [comment]
> @abhipsaMisra this object is used when timeout is specified and it is not the same as the default timeout. I haven't added it, I just corrected proxy handling.

Yes, I agree; and the changes for proxy handling look good; what I am trying to understand is - 
- Why we needed a separate `HttpClient()` object only for specifying timeout?
- The tests are all device streaming related, so is this object used in device streaming cases?

**Comment by jenoola** [comment]
Upon further investigation it was determined that the mentioned code duplication in HttpClientHelper created some dead code (httpClientObjWithPerRequestTimeout is not used in SDK code and is not exposed to customer as a part of API), so this PR should be closed and dead code should be removed.

**Comment by timtay-microsoft** [comment]
Closing this PR in lieu of #1178

**Pull request closed without merging**
