### PR TITLE
Merge from main

### PR DESCRIPTION
**Pull request by drwill-ms**

### CODE REVIEW

**Comment by timtay-microsoft** [comment]
I'm only seeing one commit here. Is it pre-squashed for some reason?

**Review by abhipsaMisra — APPROVED** [review]
Changes look good

**Comment by drwill-ms** [comment]
> I'm only seeing one commit here. Is it pre-squashed for some reason?

Oh no. I think I made a mistake by starting the merge from the actual branch and making my own branch before resolving conflicts.

**Comment by drwill-ms** [comment]
@timtay-microsoft I may have fixed it. Look better?

**Pull request merged**
