### PR TITLE
To Fix Schema Validation error for creating deployment template

### PR DESCRIPTION
**Pull request by tusharpatil11**
Per Azure portal SchemaVersion should be 2.0. 
To Fix Schema Validation error for creating deployment template -  'Deployment information could not be parsed. The schema version is not supported.'

## Checklist
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [ ] This pull-request is submitted against the `master` branch.

### CODE REVIEW

**Comment by abhipsaMisra** [comment]
Thank you for submitting this PR @tusharpatil11 !
Could you add a link to the documentation in the comments, so that we have the context for this change.

**Comment by tusharpatil11** [comment]
> Thank you for submitting this PR @tusharpatil11 !
> Could you add a link to the documentation in the comments, so that we have the context for this change.

Could you please let me which link and which documentation you want me to update?

**Comment by abhipsaMisra** [comment]
> > Thank you for submitting this PR @tusharpatil11 !
> > Could you add a link to the documentation in the comments, so that we have the context for this change.
> 
> Could you please let me which link and which documentation you want me to update?

I meant the document/ note in Azure which requires the SchemaVersion to be 2.0 for enabling creation of deployment templates.

**Comment by tusharpatil11** [comment]
> > > Thank you for submitting this PR @tusharpatil11 !
> > > Could you add a link to the documentation in the comments, so that we have the context for this change.
> > 
> > 
> > Could you please let me which link and which documentation you want me to update?
> 
> I meant the document/ note in Azure which requires the SchemaVersion to be 2.0 for enabling creation of deployment templates.

Which document, could you please share the link of the document?

**Comment by tusharpatil11** [comment]
We had issue in our JObject content while creating template. We don't need this change anymore.
Thank you!

**Pull request closed without merging**
