### PR TITLE
Amqp timeout fix

### PR DESCRIPTION
**Pull request by CIPop**
This is removing the timeout helper code. (Based on @davilu's branch).

### CODE REVIEW

**Comment by CIPop** [comment]
@davilu the token refresh failed again:

```
Assert.IsTrue failed. [3/22/2019 11:09:09 PM] Token should have been refreshed after TTL expired.

Stack trace
   at Microsoft.Azure.Devices.E2ETests.DeviceTokenRefreshE2ETests.<DeviceClient_TokenIsRefreshed_Internal>d__9.MoveNext() in D:\a\1\s\e2e\test\DeviceTokenRefreshE2ETests.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.E2ETests.DeviceTokenRefreshE2ETests.<DeviceClient_TokenIsRefreshed_Ok_Amqp>d__6.MoveNext() in D:\a\1\s\e2e\test\DeviceTokenRefreshE2ETests.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
```

**Comment by davilu** [comment]
This change is included in this PR#873

**Comment by davilu** [comment]
This change is included in this PR#873

**Pull request closed without merging**
