### PR TITLE
Increasing Fault delay to 5 seconds.

### PR DESCRIPTION
**Pull request by CIPop**
## Checklist
- [X] I have read the [contribution guidelines](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [X] This pull-request is submitted against the `master` branch.

## Description of the changes
Increasing default fault injection delay to 5 seconds.

### CODE REVIEW

**Comment by prmathur-microsoft** [comment]
@CIPop - Is this PR still valid? if so can you merge it in ?

**Comment by CIPop** [comment]
@prmathur-microsoft yes, it's still valid. No sign-off so can't merge it in.

**Pull request merged**
