### PR TITLE
Preview

### PR DESCRIPTION
**Pull request by davilu**
## Checklist
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [ ] This pull-request is submitted against the `master` branch.

### CODE REVIEW

**Comment by CIPop** [comment]
@prmathur-microsoft @davilu @tameraw  I thought we're not using `preview` anymore and instead we're going to keep everything in `master` under feature flags. Why is this needed?

**Comment by CIPop** [comment]
@davilu this is very old. What is the status of the PR?

/cc @prmathur-microsoft @tameraw

**Comment by davilu** [comment]
The PR is blocked since it's created. Device stream feature was broken and then we have DPS through MQTT issue. @ewertons already create his folk based on this and is following this change. I'm closing this PR.

**Pull request closed without merging**
