### PR TITLE
Bump versions for 2021-08-12 release

### PR DESCRIPTION
**Pull request by abhipsaMisra**
Azure IoT SDK for .NET Release 2021-08-12

## Microsoft.Azure.Devices.Client 1.38.0

- Target new DotNetty version when not net451 (#2129)
- Update reference to `Microsoft.Azure.Devices.Shared` nuget.

### Bug fixes

- Update client to accept a flag with `IDisposable` `IAuthenticationMethod` indicating if the authentication method should be disposed when the client itself is disposed. (#1911, #1954, #2003)
- Update IoT Hub CONNACK timeout to be 60 seconds (#2042, #2043)
- Update the amqp layer to inspect the inner exception for an amqp error code (#2053, #2055)
- Update connection string validation param (#2061, #2063)
- Update C2D message handler callback to not await completion of user-supplied callback (#2060)
- Clean error codes referenced and implemented by the library (#2074, #2110)

## Microsoft.Azure.Devices 1.35.0

- Add support for `DeviceScope` to import/export job (#2040)
- Update reference to `Microsoft.Azure.Devices.Shared` nuget.

### Bug fixes

- Clean error codes referenced and implemented by the library (#2074, #2110)
- Update `JobClient`, `ServiceClient`, `RegistryManager` and `DigitalTwinClient` to be mockable (#2117)

### Bug fixes

- Add `ClearAllMetadata()` to remove all metadata from the twin and the base metadata object (#1971, #1976)

## Microsoft.Azure.Devices.Provisioning.Client 1.18.0

- Update reference to `Microsoft.Azure.Devices.Shared` nuget.

### Bug fixes

- Add support for timespan timeouts to provisioning device client (#2036, #2041)

## Microsoft.Azure.Devices.Provisioning.Transport.Mqtt 1.16.0

- Update reference to `Microsoft.Azure.Devices.Shared` nuget.

### Bug fixes

- Add support for timespan timeouts to provisioning device client (#2036, #2041)
- Target new DotNetty version when not net451 (#2129)

## Microsoft.Azure.Devices.Provisioning.Transport.Amqp 1.15.0

- Update reference to `Microsoft.Azure.Devices.Shared` nuget.

### Bug fixes

- Add support for timespan timeouts to provisioning device client (#2036, #2041)

## Microsoft.Azure.Devices.Provisioning.Transport.Http 1.14.0

- Update reference to `Microsoft.Azure.Devices.Shared` nuget.

### Bug fixes

- Add support for timespan timeouts to provisioning device client (#2036, #2041)

## Microsoft.Azure.Devices.Provisioning.Security.Tpm 1.13.2

- Update reference to `Microsoft.Azure.Devices.Shared` nuget.

## Microsoft.Azure.Devices.Provisioning.Service 1.17.2

- Add the parameter name to the `ArgumentNullException` that could be thrown on `IndividualEnrollment.Attestation` initialization (#2129)
- Update reference to `Microsoft.Azure.Devices.Shared` nuget.

### CODE REVIEW

**Review by timtay-microsoft — APPROVED** [review]

**Comment by vinagesh** [comment]
Do we really need to call out all the "doc comment" updates? It makes the release notes large and does not focus on the important changes.

**Comment by timtay-microsoft** [comment]
> Also do customers understand stuff like feat etc? Should we just not call out the description instead of the commit message?

+1 to this. Customers don't care about our internal commit message title rules

**Comment by abhipsaMisra** [comment]
> Do we really need to call out all the "doc comment" updates? It makes the release notes large and does not focus on the important changes. Also do customers understand stuff like feat etc? Should we just not call out the description instead of the commit message?

We've called out doc comments in the past so I added them to our current release notes as well.
I can remove them if we decide against adding comments related notes going forward.

**Comment by abhipsaMisra** [comment]
> > Also do customers understand stuff like feat etc? Should we just not call out the description instead of the commit message?
> 
> +1 to this. Customers don't care about our internal commit message title rules

Sure. This shouldn't have made it to the release notes to begin with.

**Pull request merged**
