### PR TITLE
feat(iot-serv): Add ability to send custom authentication scopes for RBAC auth

### PR DESCRIPTION
**Pull request by timtay-microsoft**
Previously, the SDK hardcoded just "https://iothubs.azure.net/.default" as the only supported scope, but this does not work for non-public clouds

### CODE REVIEW

**Review by patilsnr — APPROVED** [review]

**Comment by SymbioticKilla** [comment]
@timtay-microsoft 
Are you sure?
Microsoft.Azure.Devices.Client 1.42.3 is from April 2024.

**Comment by timtay-microsoft** [comment]
Client package doesn't support RBAC auth, so it doesn't need configurable RBAC authentication scopes.

**Comment by SymbioticKilla** [comment]
@timtay-microsoft 
I thought that nuget updates on client side are also important changes, sorry for borrowing.

**Pull request merged**
