### PR TITLE
Bump API Version for release 2020-02-05

### PR DESCRIPTION
**Pull request by jamdavi**
## Microsoft.Azure.Devices.Client 1.35.0
 
- Add a log statement indicating a no-retry retry policy has been enabled (#1763)
- Unused memeber removal
  - `NotAllowedCharacter` from `UrlEncodedDictionarySerializer`

### Bug fixes
 
- Amqp connections are not getting disposed leaving the socket open (#1770, #1771) 
 
## Microsoft.Azure.Devices 1.30.0

- Unused memeber removal
  - `DeliveryFailureReason` enum
  - `EventHubPartitionKeyResolver` class
  - `SharedAccessSignatureAuthorizationRule` class
  - `SharedAccessSignature` class
  - `ISharedAccessSignatureCredential` interface

### CODE REVIEW

**Comment by azabbasi** [comment]
`Unused memeber removal` can be another bullet point

**Comment by azabbasi** [comment]
> `Unused memeber removal` can be another bullet point and the rest can be nested. 

or with smaller header size.

**Comment by azabbasi** [comment]
Include PR # for `Add a log statement indicating a no-retry retry policy has been enabled`

**Review by azabbasi — APPROVED** [review]
LGTM, recommended some stuff for the release notes.

**Comment by abhipsaMisra** [comment]
The retry policy related comment should be only under the device client nuget, I think you've mistakenly copied it over to the service nuget as well (our service clients currently do not have any kind of retry mechanism baked in).

**Comment by jamdavi** [comment]
> The retry policy related comment should be only under the device client nuget, I think you've mistakenly copied it over to the service nuget as well (our service clients currently do not have any kind of retry mechanism baked in).

Correct. Good catch

**Pull request merged**
