### PR TITLE
Fix Amqp token refresher time calculation

### PR DESCRIPTION
**Pull request by zolvarga**
## Checklist
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [ ] This pull-request is submitted against the `master` branch.

### CODE REVIEW

**Comment by zolvarga** [comment]
There is no more ".Seconds", ".Minutes", ".Hours" in the repo

**Comment by prmathur-microsoft** [comment]
Prod passed on this PR twice and to unblock release we are merging in.

**Pull request merged**
