### PR TITLE
Bring updates from master to preview/net5

### PR DESCRIPTION
**Pull request by abhipsaMisra**

### CODE REVIEW

**Review by timtay-microsoft — APPROVED** [review]

**Comment by timtay-microsoft** [comment]
Are we planning on releasing a preview nuget from this branch rather than from the preview branch?

**Comment by abhipsaMisra** [comment]
> Are we planning on releasing a preview nuget from this branch rather than from the preview branch?

Nope, the plan is to ship from the preview branch. 
master -> previews/net5
previews/net5 -> preview
ship from preview

**Review by vinagesh — APPROVED** [review]

**Comment by abhipsaMisra** [comment]
This merge had a type renaming missing, fixed in #1891

**Pull request closed without merging**
