### PR TITLE
Bug fix: Direct method subscription not removed after disconnect

### PR DESCRIPTION
**Pull request by tmahmood-microsoft**
After a disconnect event, when the client reconnects, client subscribes to message receive event again resulting in multiple calls to direct method callback.
The root cause was missing unsubscription after a disconnect event.

github issue: https://github.com/Azure/azure-iot-sdk-csharp/issues/3354

### CODE REVIEW

**Review by timtay-microsoft — APPROVED** [review]

**Review by abhipsaMisra — CHANGES_REQUESTED** [review]
RemoveOldOperations is called at regular intervals to remove older pending twin operation tasks from our internal collection.
Unhooking the disconnection and received message event handlers in the same function isn't what you want to do, since what will happen here is even without any disconnection event the handlers are getting unhooked after a certain interval.
Instead, you need to unhook the message processor as a part of the transport handler's disconnection detection block.

**Comment by tmahmood-microsoft** [comment]
Updated and unhooking the message processor as a part of the transport handler's disconnection detection block.

**Comment by abhipsaMisra** [comment]
What scenarios did you test for this?
Can we add some tests so that we don't regress in the future?
For a unit test you could set up a mock client and trigger the disconnection event handler. Then, verify that the message processor handler was unhooked. As a bonus, you can also test that no other operation was executed on the client, i.e. no other handlers were attached or detached.

**Review by patilsnr — COMMENTED** [review]
Agree about adding a test, but otherwise makes sense.

**Review by abhipsaMisra — APPROVED** [review]

**Review by patilsnr — APPROVED** [review]

**Pull request merged**
