### PR TITLE
[DO NOT MERGE] Bring master to preview

### PR DESCRIPTION
**Pull request by bikamani**
Cherry-picking commits since [this](https://github.com/Azure/azure-iot-sdk-csharp/commit/f1da7a2142541ba4036be0987e14bdabc88aecf5)

### CODE REVIEW

**Comment by vinagesh** [comment]
I know you resolved conflicts on the second commit but it might be good to keep the same commit name as in master so that if we check to find if a commit is here, we know it is here.

**Comment by bikamani** [comment]
> ts on the second commit but it might be good to keep the same commit name as in master so that if we check to find if a commit is here, we know it

noted, agreed.

**Comment by timtay-microsoft** [comment]
Wait, why are you cherry picking? Can't you just merge master into preview?

**Comment by bikamani** [comment]
> Wait, why are you cherry picking? Can't you just merge master into preview?

Yes we can do merge too, there were only 3 commits so I did cherry picking. This approach was simpler as not much conflict.

**Comment by prmathur-microsoft** [comment]
> These are not all the commits that separate master and preview. Please do a full merge from master into preview, not a cherry pick of just the PnP commits

I agree we should bring in all commits into preview before release. It is fine to unblock yourselves by cherrypicking and coding samples. But finally we need master and preview to be aligned before release.

**Comment by bikamani** [comment]
Not required anymore.

**Comment by bikamani** [comment]
> > These are not all the commits that separate master and preview. Please do a full merge from master into preview, not a cherry pick of just the PnP commits
> 
> I agree we should bring in all commits into preview before release. It is fine to unblock yourselves by cherrypicking and coding samples. But finally we need master and preview to be aligned before release.

Agreed, it is taken care of now.

**Pull request closed without merging**
