### PR TITLE
Cherry-picking commits from master for 6/28/2019 release

### PR DESCRIPTION
**Pull request by abhipsaMisra**
- Cherry picked commits from `master`.
- Versions are bumped.

### CODE REVIEW

**Comment by abhipsaMisra** [comment]
Builds triggered:
Canary - https://azure-iot-sdks.visualstudio.com/azure-iot-sdks/_build/results?buildId=24858&view=results
WestUS - https://azure-iot-sdks.visualstudio.com/azure-iot-sdks/_build/results?buildId=24859&view=results
Horton - https://azure-iot-sdks.visualstudio.com/azure-iot-sdks/_build/results?buildId=24860&view=results
Horton fault-injection - https://azure-iot-sdks.visualstudio.com/azure-iot-sdks/_build/results?buildId=24861&view=results

**Comment by abhipsaMisra** [comment]
Build results:
Canary - 1 test failed on windows

- `Service client exception`
```
Test method Microsoft.Azure.Devices.E2ETests.MessageReceiveE2EPoolAmqpTests.Message_IoTHubSak_DeviceReceiveSingleMessage_MultipleConnections_AmqpWs threw exception: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'FaultTolerantAmqpObject`1'.

at Microsoft.Azure.Devices.AmqpServiceClient.SendAsync(String deviceId, Message message, Nullable`1 timeout) in D:\a\1\s\iothub\service\src\AmqpServiceClient.cs:line 155
   at Microsoft.Azure.Devices.E2ETests.MessageReceiveE2EPoolAmqpTests.<>c__DisplayClass12_0.<<ReceiveMessagePoolOverAmqp>b__0>d.MoveNext() in D:\a\1\s\e2e\test\MessageReceiveE2EPoolAmqpTests.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Devices.E2ETests.PoolingOverAmqp.TestPoolAmqpAsync(String devicePrefix, TransportType transport, Int32 poolSize, Int32 devicesCount, Func`3 initOperation, Func`3 testOperation, Func`2 cleanupOperation, ConnectionStringAuthScope authScope) in D:\a\1\s\e2e\test\PoolingOverAmqp.cs:line 78
   at Microsoft.Azure.Devices.E2ETests.MessageReceiveE2EPoolAmqpTests.ReceiveMessagePoolOverAmqp(TransportType transport, Int32 poolSize, Int32 devicesCount, ConnectionStringAuthScope authScope) in D:\a\1\s\e2e\test\MessageReceiveE2EPoolAmqpTests.cs:line 156
   at Microsoft.Azure.Devices.E2ETests.MessageReceiveE2EPoolAmqpTests.Message_IoTHubSak_DeviceReceiveSingleMessage_MultipleConnections_AmqpWs() in D:\a\1\s\e2e\test\MessageReceiveE2EPoolAmqpTests.cs:line 106
```
WestUS - Green
Horton - Green
Horton fault-injection - Tests failed

/cc @prmathur-microsoft : Since WestUS is green, and canary failure is a known service client issue, we can continue with the release.

**Comment by CIPop** [comment]
> Horton fault-injection - Tests 

@abhipsaMisra - these were passing before. What was the exception?

/cc @varunpuranik FYI

**Comment by abhipsaMisra** [comment]
@CIPop It fails with the below error message:
```
msrest.exceptions.ClientRequestError: Error occurred in request., ConnectionError: HTTPConnectionPool(host='localhost', port=8083): Max retries exceeded with url: /module/module_9/twin (Caused by ReadTimeoutError("HTTPConnectionPool(host='localhost', port=8083): Read timed out. (read timeout=60)"))
```
/cc @YoDaMa - It looks like we've been seeing the above error on horton fault-injection tests for a while now. Could you give this a look - https://azure-iot-sdks.visualstudio.com/azure-iot-sdks/_build?definitionId=220&_a=summary.

**Pull request merged**
