### PR TITLE
chore: update link for IoT help and msft Q&A

### PR DESCRIPTION
**Pull request by elhorton**
## Checklist
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [ ] This pull-request is submitted against the `master` branch.

### CODE REVIEW

**Comment by elhorton** [comment]
(copying from similar PR in Java repo) 

Hi all, these are a few simple changes to our github support workflow for a couple of reasons:

adding reference to Microsoft Q&A, the new, preferred platform for CSS engineers, MVPs, and Microsoft cloud experts to answer questions. We're trying to direct as much traffic on general questions there as possible so they don't show up as Github issues

adjusting the link to the official Azure IoT Support page to a vanity link so that we can track how many redirects we have (important for the Azure Customer Experience team to measure success of these workflows).

Let me know if you have any questions or concerns, thanks!

**Comment by abhipsaMisra** [comment]
@elhorton Is this ready to be merged in? If yes, I can run it through the gate and have this merged in?

**Comment by elhorton** [comment]
yes it's ready, thanks @abhipsaMisra

**Pull request merged**
