### PR TITLE
Amqp transport redesign

### PR DESCRIPTION
**Pull request by zolvarga**
## Checklist
- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [ ] This pull-request is submitted against the `master` branch.

### CODE REVIEW

**Comment by abhipsaMisra** [comment]
Build started: https://azure-iot-sdks.visualstudio.com/azure-iot-sdks/_build/results?buildId=11580

**Comment by prmathur-microsoft** [comment]
@davilu please review.

**Comment by davilu** [comment]
@zolvarga Could you please run CodeFormatter: `CodeFormatter.exe <csproj_file_path>` The bits can be downloaded from https://github.com/dotnet/codeformatter/releases

**Pull request merged**
