### PR TITLE
Make DeviceClient & ModuleClient open & extensible

### LINKED ISSUE #1791: [feature request] Make DeviceClient extensible
**Is your feature request related to a problem? Please describe.**
Make DeviceClient extensible so that we can build upon it, mock it, etc.

**Describe the solution you'd like**
I'm happy to open a PR to remove the `sealed` keyword on the class so that we can extend it.

**Describe alternatives you've considered**
N/A

**Additional context**
Relates to https://github.com/Azure/azure-iot-sdk-csharp/issues/61 & https://github.com/Azure/azure-iot-sdk-csharp/issues/110 which blocks us from writing tests as well.

Thank you for helping make this project even better!

### PR DESCRIPTION
**Pull request by tomkerkhove**
## Checklist
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [x] This pull-request is submitted against the `master` branch.

## Description of the changes
Make DeviceClient extensible so that we can build upon it, mock it, etc.

## Reference/Link to the issue solved with this PR (if any)
Fixes #1791

### CODE REVIEW

**Comment by vinagesh** [comment]
There are some warnings that we need to fix. Will be looking into it before checking it in.

**Comment by tomkerkhove** [comment]
Is there something I should do?

Sounds like you need to fix something at your end or not?

**Comment by vinagesh** [comment]
> Is there something I should do?
> 
> Sounds like you need to fix something at your end or not?

Nope. We will fix it and check it in soon.

**Pull request closed without merging**
