### PR TITLE
Update shared csproj to use SolutionDir for dependencies

### PR DESCRIPTION
**Pull request by myagley**
Solutions including the device client as a git submodule cannot resolve dependencies properly.

### CODE REVIEW

**Comment by nayato** [comment]
@myagley same goes for `PCLCrypto` dependency in `Microsoft.Azure.Devices.Client.csproj`

**Comment by myagley** [comment]
@nayato updated for PCLCrypto

**Comment by tameraw** [comment]
@myagley - Thanks for the pull request. Coincidentally a check-in is in flight addressing the same issue. We'll keep this one open until the fix is checked in.

**Comment by tameraw** [comment]
Closing as a fix for this has been checked in.
@myagley - Thanks again for providing this PR and let us know if you face any issues.

**Pull request closed without merging**
