### PR TITLE
Publish etl artifact and trx test run result.

### PR DESCRIPTION
**Pull request by abhipsaMisra**
## Checklist
- [x] I have read the [contribution guidelines](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- [x] This pull-request is submitted against the `master` branch.

## Description of the changes

Adding ETL log result to VSTS windows build artifact.

### CODE REVIEW

**Comment by CIPop** [comment]
@prmathur-microsoft this is blocking investigations on why things fail. 
Running tests is pointless since AZP will not pick up the new YAML files. We need this merged ASAP.

**Comment by prmathur-microsoft** [comment]
Got a green signal from the team to merge this. So using admin privileges to merge.

**Pull request merged**
