### PR TITLE
The build will no longer be corrupted by a user's powershell profile.

### PR DESCRIPTION
**Pull request by idavis**
# Checklist
- [x] I have read the [contribution guidelines] (https://github.com/Azure/azure-iot-sdk-c/blob/master/.github/CONTRIBUTING.md).
- [ ] I added or modified the existing tests to cover the change (we do not allow our test coverage to go down).
- If this is a modification that impacts the behavior of a public API
  - [ ] I edited the corresponding document in the `devdoc` folder and added or modified requirements.
- I submitted this PR against the correct branch: 
  - [x] This pull-request is submitted against the `master` branch. 

# Reference/Link to the issue solved with this PR (if any)

# Description of the problem

The build was inheriting the current powershell profile breaking the build in certain scenarios and making its success variable.

# Description of the solution
 
Configured powershell to no longer use the user profile when running.

### CODE REVIEW

**Comment by CIPop** [comment]
Thanks @idavis ! 
This should probably be changed in the linux bash script as well?

**Comment by idavis** [comment]
Yes, it will have to change as well. I hadn't expect the sh to be using PowerShell.

**Comment by idavis** [comment]
@CIPop I have updated the PR with the linux change as well, but I can't test it at the moment.

**Comment by CIPop** [comment]
Thanks @idavis ! 
No worries: we merge through a CI system that uses this script on Linux.

**Pull request merged**
